### ISSUE TITLE
Release to Playstore 

### ISSUE THREAD

**Issue by Dunky13** [SebastianSarbu/PizzaWatchFace#1]
I really like the design, found this through [HackADay](https://hackaday.com/2022/06/27/developing-a-custom-wearos-watch-face/) 

Would love to use & install it on my watch, if/when release in Playstore.

Using Pixel Minimal Watch Face and it comes close. But I feel like I'm going to like this better.

**Comment by SebastianSarbu** [comment]
Hello!

I will try to release it during the next two weeks. 
Thank you very much for your interest

**Comment by Dunky13** [comment]
Still waiting for the release 🥰

**Comment by SebastianSarbu** [comment]
I am sorry for this delay. I have uploaded the code on Saturday after I made some modifications to be compliant to the store rules. The publication is still pending, I have contacted Google support and they said it is still in review because they have a lot of work lately. I promise I haven't forgotten, we just have to wait a little more.

**Comment by SebastianSarbu** [comment]
Hello! 

I am glad to announce that the release was finally published to store.
Please find the link attached here and let me know if it works:
https://play.google.com/store/apps/details?id=com.asebastian.com.asebastian.pizzawatchface

Regards,
Sebi

**Comment by Dunky13** [comment]
I'm getting an error: "your device is not compatible" on my pixel 6 pro. I have my TicWatch Pro 3 connected. I cant find it in the Playstore on my watch either. 😔

**Comment by SebastianSarbu** [comment]
After creating a ticket to Google, it seems that the app is not compliant to their policies due to a deprecated method. I'll have to update the app and redo the publishing process

**Comment by Dunky13** [comment]
Any update on this?

**Comment by SebastianSarbu** [comment]
Hello! Unfortunately I gave up on this project, for now. The Google support was disappointing and I am not planning on continuing this project, at least this year. I have personal things I also need to take care of.

In the meantime, please use the steps from the video and upload the watch via Android Studio.
